---
- name: run playbook
  hosts: all
  tasks:
    - name: download package
      yum:
        name: tree
        state: present
      register: package_download

    - name: print 
      debug:
        var: "{{ package_download }}"
